//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbVTEntities : DbContext
    {
        public dbVTEntities()
            : base("name=dbVTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Live_List> Live_List { get; set; }
        public virtual DbSet<Member_List> Member_List { get; set; }
        public virtual DbSet<tIntro> tIntro { get; set; }
        public virtual DbSet<tIntro_en> tIntro_en { get; set; }
        public virtual DbSet<tIntro_jp> tIntro_jp { get; set; }
        public virtual DbSet<tMember> tMember { get; set; }
        public virtual DbSet<tMember_en> tMember_en { get; set; }
        public virtual DbSet<tMember_jp> tMember_jp { get; set; }
        public virtual DbSet<tToDo> tToDo { get; set; }
        public virtual DbSet<tToDo_en> tToDo_en { get; set; }
        public virtual DbSet<tToDo_jp> tToDo_jp { get; set; }
        public virtual DbSet<Video_List> Video_List { get; set; }
        public virtual DbSet<VTuber_List> VTuber_List { get; set; }
        public virtual DbSet<Tweet_List> Tweet_List { get; set; }
    }
}
