//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMember_en
    {
        public int tId { get; set; }
        public string tName { get; set; }
        public string tjpName { get; set; }
        public string tTitle { get; set; }
        public string tNick { get; set; }
        public string tSex { get; set; }
        public Nullable<System.DateTime> tBirth { get; set; }
        public string tHeight { get; set; }
        public string tInterest { get; set; }
        public string tHate { get; set; }
        public string tStar { get; set; }
        public string tAge { get; set; }
        public string tLanguage { get; set; }
        public int tMemberId { get; set; }
    }
}
