//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet_List
    {
        public string twitterid { get; set; }
        public string tweetsid { get; set; }
        public Nullable<System.DateTime> tweet_created_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
