//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTuber_List
    {
        public string yt_channel_id { get; set; }
        public string yt_channel_name { get; set; }
        public string org { get; set; }
        public string suborg { get; set; }
        public string photo { get; set; }
        public string twitter { get; set; }
        public int subscriber_count { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> crawled_at { get; set; }
    }
}
